### ISSUE TITLE
jCanvas problems with animateLayer (rotate) after bumping jQuery to 3.2.0 (firefox only)

### ISSUE THREAD

**Issue by mbienkowski** [caleb531/jcanvas#278]
Js stack after trying to rotate: 
```
TypeError: elem.getClientRects is not a function[More info...]  jquery-3.2.0.js:9975:9
	.offset http://.../jquery-3.2.0.js:9975:9
	$.event.fix http://.../jcanvas.js:2356:13
	jQuery.event.dispatch http://.../jquery-3.2.0.js:5165:15
	jQuery.event.add/elemData.handle http://.../jquery-3.2.0.js:5014:6
```

**Comment by caleb531** [comment]
This is a known bug, and I believe I have a patch for it already (just not yet released into stable). Please try this experimental build (link below) and see if it fixes the error for you:

https://github.com/caleb531/jcanvas/blob/jquery-3/jcanvas.js

**Comment by caleb531** [comment]
@mbienkowski, have you tried my patch? Please let me know how it works for you! :)

**Comment by echonox** [comment]
@caleb531 had same error, and tested your exp build and works fine, could you plz, also I see that it is 1 commit behind master could you plz merge and let me know, we use jcanvas in our project, tnx.

**Comment by caleb531** [comment]
@echonox Sure! The jQuery 3 patch has now been merged into `master`. Granted, I have a few more changes to make/review before I am ready to push a new stable release, but you are welcome to start using the latest `jcanvas.js` source anytime (the minified file has not been regenerated yet).

**Comment by echonox** [comment]
@caleb531 tnx
